---
- name: Deploy Strava Title Updater
  hosts: vps
  become: yes
  roles:
    - role: strava
      vars:
        repo_url: "https://github.com/ninjatuna3527/strava_title_updater.git"
        repo_branch: "main"
        strava_client_id: "{{ lookup('env', 'STRAVA_CLIENT_ID') }}"
        strava_client_secret: "{{ lookup('env', 'STRAVA_CLIENT_SECRET') }}"
        base_path: "{{ lookup('env', 'BASE_PATH') }}"
        callback_hostname: "{{ lookup('env', 'CALLBACK_HOSTNAME') }}"
        deploy_ssh_key: "{{ lookup('env', 'DEPLOY_SSH_KEY') }}"